<?php

namespace codewild\csubmboer\models;

use codewild\phpmvc\db\BaseDbModel;
use codewild\phpmvc\DbFile;

class DataFile extends DbFile
{

    static public function tableName(): string
    {
        return 'data_files';
    }

    public string $title = '';

    public static function attributes(): array
    {
        $output = parent::attributes();
        $output[] = 'title';
        return $output;
    }

    public function rules(): array{
        return [
            'title' => [self::RULE_REQUIRED],
//            'type' => [[self::RULE_CONTAINS, 'contains' => []]],
//            'size' => [[self::RULE_MAX, 'max' => 1000000]],
        ];
    }

    public function labels(): array
    {
        $output = parent::labels();
        $output['dataFileId'] = 'Uploaded Models';
        return $output;
    }

    public function create(string $scriptId){
        if ($this->save()){
            return (DataNav::create(self::lastInsertId(), $scriptId));
        }
        return false;
    }

    public function delete()
    {
        if ($this->size === 0){
            // REMOTE LOCATION, STEP OVER DBFILE METHOD
            return BaseDbModel::delete();
        } else {
            // LOCAL LOCATION, STEP INTO DBFILE METHOD
            return parent::delete(); // TODO: Change the autogenerated stub
        }
    }
}
